apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mariadb
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/pv-mariadb
