apiVersion: v1
kind: ConfigMap
metadata:
  name: config-mariadb
  namespace: default
data:
  MYSQL_ROOT_PASSWORD: somewordpress
  MYSQL_DATABASE: wordpress
  MYSQL_USER: wordpress
  MYSQL_PASSWORD: wordpress
